-- PredictMarket reproducible development seeds

BEGIN;

-- Categories
INSERT INTO categories (id, name, slug, icon) VALUES
  ('10000000-0000-0000-0000-000000000001', 'Politics', 'politics', '🏛️'),
  ('10000000-0000-0000-0000-000000000002', 'Technology', 'technology', '🤖'),
  ('10000000-0000-0000-0000-000000000003', 'Sports', 'sports', '🏈'),
  ('10000000-0000-0000-0000-000000000004', 'Finance', 'finance', '📈'),
  ('10000000-0000-0000-0000-000000000005', 'Entertainment', 'entertainment', '🎬'),
  ('10000000-0000-0000-0000-000000000006', 'Science', 'science', '🔬')
ON CONFLICT (id) DO NOTHING;

-- Users (admin + demo)
INSERT INTO users (id, username, email, password_hash, wallet_balance, streak_count, rank) VALUES
  ('20000000-0000-0000-0000-000000000001', 'admin', 'admin@predictmarket.com', '$2b$10$4lxMRY4zVfQegh7iWj5ly.F6rYp84mP2x7jVPPxw8jArfmkWri6N2', 999999.00, 30, 'Legend'),
  ('20000000-0000-0000-0000-000000000002', 'alice_oracle', 'alice@example.com', '$2b$10$8YQfiG6fN0Wf8Yx4Jx1U8eLh4xgjJzj4I5Pjz0d78q5M0qz6yD2h2', 4200.00, 14, 'Oracle'),
  ('20000000-0000-0000-0000-000000000003', 'bob_trader', 'bob@example.com', '$2b$10$Qk0H5s7mQhWcn3d7Jk1bPuxM6N3e4k8z2M9KXJwGh9fE8Tq7h0a1u', 1800.00, 5, 'Analyst'),
  ('20000000-0000-0000-0000-000000000004', 'carol_wins', 'carol@example.com', '$2b$10$5XxO8jWzq3Ff8nS0VYQyt.rWwCq8Y5mQW7J8H4Fh9Q2Qm4o3qfY9.', 5000.00, 20, 'Expert'),
  ('20000000-0000-0000-0000-000000000005', 'dave_bets', 'dave@example.com', '$2b$10$R3P2Y0x7qkN4a8mC9vD6tebWwQ5kF7L3mN1sT9zX0cV2bH4jK6d7e', 1200.00, 2, 'Novice'),
  ('20000000-0000-0000-0000-000000000006', 'eve_predicts', 'eve@example.com', '$2b$10$A7Yk2Qf8n3P4sD6hJ1lVre9mC0xW7zN5bF3kT8qP2mV6dH1sL4c9u', 2600.00, 8, 'Expert')
ON CONFLICT (id) DO NOTHING;

-- Seed a known admin user `pratham@gmail.com` with bcrypt password generated by pgcrypto
INSERT INTO users (id, username, email, password_hash, wallet_balance, streak_count, rank)
VALUES
  ('20000000-0000-0000-0000-000000000007', 'pratham', 'pratham@gmail.com', crypt('07896811Pp@', gen_salt('bf')), 999999.00, 0, 'Legend')
ON CONFLICT (email) DO UPDATE
SET password_hash = EXCLUDED.password_hash,
    username = EXCLUDED.username,
    wallet_balance = EXCLUDED.wallet_balance,
    rank = EXCLUDED.rank;

-- Markets (2 total)
INSERT INTO markets (id, title, description, category_id, creator_id, yes_volume, no_volume, resolution_side, status, expires_at, image_url, created_at) VALUES
  ('30000000-0000-0000-0000-000000000001', 'Is 2C22 the undisputed champion of complaining to DOAA/DOSA', 'Predict whether 2C22 is the undisputed champion of complaining to DOAA/DOSA.', '10000000-0000-0000-0000-000000000002', '20000000-0000-0000-0000-000000000001', 920.00, 610.00, NULL, 'OPEN', NOW() + INTERVAL '3 days', NULL, NOW() - INTERVAL '5 days'),
  ('30000000-0000-0000-0000-000000000002', 'Will we get max marks in DBMS project', 'yayyyyyyyyyyyyyyyyyyyyyyyyyy letssss''go', '10000000-0000-0000-0000-000000000005', '20000000-0000-0000-0000-000000000001', 0.00, 0.00, NULL, 'OPEN', NOW() + INTERVAL '1 day', 'https://res.cloudinary.com/dduzorsii/image/upload/v1778128450/ChatGPT_Image_May_7_2026_10_02_30_AM_cuwpnb.png', NOW())
ON CONFLICT (id) DO NOTHING;

-- Bets (2 total)
INSERT INTO bets (id, user_id, market_id, side, amount, shares, potential_payout, status, created_at) VALUES
  ('40000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000002', '30000000-0000-0000-0000-000000000001', 'YES', 120.00, 199.3377, 199.34, 'OPEN', NOW() - INTERVAL '12 hours'),
  ('40000000-0000-0000-0000-000000000002', '20000000-0000-0000-0000-000000000003', '30000000-0000-0000-0000-000000000001', 'NO', 80.00, 200.0000, 200.00, 'OPEN', NOW() - INTERVAL '9 hours')
ON CONFLICT (id) DO NOTHING;

-- Leaderboard baseline
INSERT INTO leaderboard_scores (id, user_id, score, wins, losses, total_wagered, updated_at) VALUES
  ('50000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000002', 1220.00, 4, 2, 980.00, NOW()),
  ('50000000-0000-0000-0000-000000000002', '20000000-0000-0000-0000-000000000003', 410.00, 2, 3, 750.00, NOW()),
  ('50000000-0000-0000-0000-000000000003', '20000000-0000-0000-0000-000000000004', 1630.00, 6, 1, 1320.00, NOW()),
  ('50000000-0000-0000-0000-000000000004', '20000000-0000-0000-0000-000000000005', -320.00, 1, 5, 640.00, NOW()),
  ('50000000-0000-0000-0000-000000000005', '20000000-0000-0000-0000-000000000006', 870.00, 3, 2, 910.00, NOW())
ON CONFLICT (user_id) DO UPDATE
SET score = EXCLUDED.score,
    wins = EXCLUDED.wins,
    losses = EXCLUDED.losses,
    total_wagered = EXCLUDED.total_wagered,
    updated_at = EXCLUDED.updated_at;

-- Comments
INSERT INTO comments (id, user_id, market_id, content, created_at) VALUES
  ('60000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000002', '30000000-0000-0000-0000-000000000001', 'Model capability jumps are accelerating this year.', NOW() - INTERVAL '8 hours')
ON CONFLICT (id) DO NOTHING;

COMMIT;

DO $$
BEGIN
  RAISE NOTICE 'Seed complete: categories=%, users=%, markets=%, bets=%',
    (SELECT COUNT(*) FROM categories),
    (SELECT COUNT(*) FROM users),
    (SELECT COUNT(*) FROM markets),
    (SELECT COUNT(*) FROM bets);
END;
$$;
